version: 2
updates:
  # GitHub Actions in /.github/workflows/
  - package-ecosystem: "github-actions"
    # "/" == "/.github/workflows/"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
      timezone: "America/Montreal"
    groups:
      gh-actions:
        patterns:
          - "actions/*"
    open-pull-requests-limit: 7
