name: MT update SSL cert
on:
  workflow_dispatch: # manual
  schedule:
    - cron: '0 18 2 * *' # Monthly on the 2nd @ 6pm UTC # WEEKLY https://crontab.guru/#0_18_2_*_*
# gh workflow run mt-update-ssl-cert.yml --ref mmathieum
# gh run list --workflow=mt-update-ssl-cert.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  # git commit & push
  MT_ORG_GIT_COMMIT_ON: ${{ secrets.MT_ORG_GIT_COMMIT_ON }}
  MT_ORG_GIT_COMMIT_OFF: ${{ secrets.MT_ORG_GIT_COMMIT_OFF }}
  MT_GIT_COMMIT_ON: ${{ secrets.MT_GIT_COMMIT_ON }}
  MT_GIT_COMMIT_OFF: ${{ secrets.MT_GIT_COMMIT_OFF }}
jobs:
  MT-UPDATE-SSL-CERT-JOB:
    name: "MT Update SSL cert"
    runs-on: ubuntu-latest
    steps:
      - name: MT check out main repository code (with submodule)
        uses: actions/checkout@v4
        with:
          ref: mmathieum
          submodules: true # required to set right token
          token: ${{ secrets.MT_PAT }}
          fetch-depth: 0 # fetch all (not required util release build)
      - name: MT check out submodules
        run: ./checkout_submodules.sh
      - name: MT setup MT_GIT_BRANCH env
        if: github.event_name != 'pull_request'
        run: |
          echo "MT_GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: MT code sync
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: ./commons/code_sync.sh
      - name: MT set is commit enabled
        run: |
          source ./commons/commons.sh
          setGitCommitEnabled
          setGitUser
          echo "MT_GIT_COMMIT_ENABLED=$MT_GIT_COMMIT_ENABLED" >> "$GITHUB_ENV"
      - name: MT fetch latest SSL cert
        run: |
          openssl s_client -connect stm.info:443 2>/dev/null </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > commons-android/src/main/res/raw/info_stm_pem
          openssl s_client -connect api.stm.info:443 -legacy_server_connect 2>/dev/null </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > app-android/src/main/res/raw/info_stm_api_pem
      - name: MT commit change
        if: env.MT_GIT_COMMIT_ENABLED == 'true'
        run: |
          git -C commons-android add src/main/res/raw/info_stm_pem
          git -C commons-android  diff --staged --quiet || git -C commons-android commit -m "CI: Update stm.info SSL cert"
          git -C commons-android push
          git -C app-android add src/main/res/raw/info_stm_api_pem
          git -C app-android  diff --staged --quiet || git -C app-android commit -m "CI: Update info.stm.info SSL cert"
          git -C app-android push
        env:
          GITHUB_TOKEN: ${{ secrets.MT_PAT }}
